### ISSUE TITLE
Can't import in a Docusaurus project - error `can't resolve 'http'`

### ISSUE THREAD

**Issue by AchrafAmil** [asyncapi/asyncapi-react#734]
**Description**

My goal is to deploy two docs (OpenAPI & AsyncAPI) together in the same place.

1. I generate a Docusaurus website using steps [docusaurus-openapi](https://github.com/cloud-annotations/docusaurus-openapi). The result is at the "[Initial commit](https://github.com/AchrafAmil/DocusaurusAsyncAPI/commit/8831421b730d50dc53ad2507f1e36b1ec02d49e9)" of the [reproducible minimal example](https://github.com/AchrafAmil/DocusaurusAsyncAPI).

2. I add a custom react page as described in [their doc](https://docusaurus.io/docs/creating-pages#add-a-react-page) and import a random react component in it ('awesome-react-button'), and it works:

<img width="1800" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/7039320/4f23ae39-a737-446f-b440-033bc6058057">

3. I import the AsyncAPI React component (exact diff [commit](https://github.com/AchrafAmil/DocusaurusAsyncAPI/commit/7370bc343020ff4a6632fa72edc58b9474e63bab)) but now it crashes:

<img width="1798" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/7039320/59e6eef0-337f-48e3-9c51-e99a014ba423">

**Expected result**

Import to work and not break everything.

**Actual result**

Compilation errors

<details>
<summary>Full errors snippet</summary>

```
Module not found: Error: Can't resolve 'http' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/Users/achraf/exp_docs/docusaurus/my-website/node_modules/@docusaurus/core/node_modules, node_modules, /Users/achraf/exp_docs/docusaurus/my-website/node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
Module not found: Error: Can't resolve 'https' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }
Module not found: Error: Can't resolve 'stream' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/avsc/etc/browser'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
Module not found: Error: Can't resolve 'stream' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/avsc/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
Module not found: Error: Can't resolve 'zlib' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/avsc/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }
Module not found: Error: Can't resolve 'stream' in '/Users/achraf/exp_docs/docusaurus/my-website/node_modules/avsc/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
client (webpack 5.88.0) compiled with 6 errors
```

</details>

**Steps to reproduce**

Checkout before/after this commit in the reproducible: https://github.com/AchrafAmil/DocusaurusAsyncAPI/commit/7370bc343020ff4a6632fa72edc58b9474e63bab

**Troubleshooting**

Web dev is really not my comfort zone so I might be doing/saying something wrong, but it seems like the AsyncAPI React component is using a node.js dependency that shouldn't be there (?).

**Comment by fmvilas** [comment]
Yup, it looks like Docusaurus is a pure client-side app. AsyncAPI React component is not purely client-side but we're publishing a client-side version of it that I guess that's what you should be using.

Can you try using the `next` version? https://github.com/asyncapi/asyncapi-react/tree/next. You'll find docs there on how to use it even though the rewrite is not finished yet it's pretty close to be done.

cc @magicmatatjahu

**Comment by derberg** [comment]
@AchrafAmil please check with latest release candidate -> [v1.0.0-next.48](https://github.com/asyncapi/asyncapi-react/releases/tag/v1.0.0-next.48)

@fmvilas `AsyncAPI React component is not purely client-side` - react component is definitely client side, not sure what you mean

**Comment by AchrafAmil** [comment]
Just [tried v1.0.0-next.48](https://github.com/AchrafAmil/DocusaurusAsyncAPI/commit/9d04ce9a0eb7ec1d87e2f64a9bae2ea9401fad1e) and I still get the same error.

**Comment by fmvilas** [comment]
It is not because it depends on the AsyncAPI parser that access the Node.js fs package. Last time I checked, we were using browserify to make it browser-compatible. Not sure it's still the same.

**Comment by derberg** [comment]
`asyncapi-react` still uses old parser. And yes, in old parser there are some file system operations, and also there is `node-fetch` used when you do `parseFromUrl` but that is what browserify/webpack/younameit 🤷 the fact that you use them make your package also client-side, because I use package, and don't care about source code. But yeah, just my opinion 😛 

@AchrafAmil the reason is https://github.com/APIDevTools/json-schema-ref-parser/blob/v9.0.6/lib/resolvers/http.js#L3 and after short investigation I think it is because of the node version that you are using 🤔 so `http` and also `https` are native node packages. Last time in their docs they say to use it like `require('http')` is Node 14, the new ones like 16 and up say `require('node:http')`. So I think you are using Node higher than 14 and it complains about `require('http')` because it by default things it is a broken local code file reference.

Try to use Node 14, maybe that helps

**Comment by AchrafAmil** [comment]
@derberg I can't force Node 14 as it's not supported by facebook/docusaurus

```
@docusaurus/core@2.4.1: The engine "node" is incompatible with this module. Expected version ">=16.14". Got "14.21.3"
```

**Comment by AchrafAmil** [comment]
and if I "ignore engines" I get this (very likely some new syntax that node 14 can't get)

```
file:///Users/achraf/exp_docs/docus2/myws/node_modules/@docusaurus/core/bin/docusaurus.mjs:30
process.env.BABEL_ENV ??= 'development';
                      ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
    at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by derberg** [comment]
oh not cool 😞 

you have 2 options:
- wait once we migrate to use in react the new v2 parser that uses different package that do not use `http` dependency. I cannot commit to any dates. Unless @fmvilas planned something already
- you can try workaround this problem with https://www.npmjs.com/package/module-alias if you are in rush. Below you see chatgpt hint that sounds like it could work 
    ![Screenshot 2023-06-29 at 11.12.37.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_06_29_at_11_12_37_aa025795c9.png)

**Comment by kennethaasan** [comment]
still an issue

**Comment by MartinMuzatko** [comment]
Still an issue.

**Comment by AchrafAmil** [comment]
FWIW, I went for the (pretty savage but quick) workaround of simply putting the fat single-file html+css+javascript in a React component. It gives the following results: https://docs.nabla.com/server/copilot-listen-ws
