### ISSUE TITLE
Payload property named message breaks with null value

### ISSUE THREAD

**Issue by ly29** [asyncapi/asyncapi-react#797]
**Payload property named message breaks with null value**

```        "payload": {
          "type": "object",
          "properties": {
            "message": {
              "type": ["string", "null"],
              "maxLength": 50
            }
          },
          "required": ["message"],
        },
        "examples": [{
            "name": "return",
            "payload": {
              "message": null
            }
          }
        ]
      }```


It breaks rendering of the asyncapi spec, validation does not give valid errors and studio.asyncapi.com breaks


<!-- Provide relevant technical details such as the browser name and version, or the operating system. -->


**Expected result**
It works and renders. Note that this works if the message property is renamed or given a non null example value.

<!-- Describe what you expect to happen. -->

**Actual result**


The following error is given 
```
	Error thrown during AsyncAPI document validation. Name: Error, message: jsonPath: Cannot read properties of null (reading 'schemaFormat'): _$_property === 'message' && _$_v.schemaFormat === void 0, stack: Error: jsonPath: Cannot read properties of null (reading 'schemaFormat'): _$_property === 'message' && _$_v.schemaFormat === void 0 at v._eval (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4494941) at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4491179 at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493697 at Array.forEach (<anonymous>) at v._walk (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493676) at v._trace (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4491130) at v._trace (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4490522) at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4490621 at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493697 at Array.forEach (<anonymous>)
```
<!-- Describe what happens instead. -->

**Steps to reproduce**

<!-- List the steps to follow to reproduce the bug. Attach any files, links, code samples, or screenshots that could help in investigating the problem. -->
Paste the following gist into the asyncapi studio
https://gist.github.com/ly29/6b56cc8252ad48ac681f19ea468d540f

**Troubleshooting**
I have reduced the issue down to one specific property that breaks.
<!-- Describe the steps you have already taken to solve the issue. -->

**Comment by derberg** [comment]
thanks for the issue, 

so basically even though the message type is a tuple of `string` and `null` the example with `"message": null` throws an issue, but if you change to `"message": "test"` it works fine

this is a validation issue, cannot be fixed in the react component. Moving to parser
